modLoader="javafml"
loaderVersion="[39,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=${mod_id}"
displayURL="${mod_homepage}"
logoFile="${mod_id}_banner.png"
logoBlur=false
authors="${mod_author}"
description="${mod_desc}"

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="framework"
    mandatory=true
    versionRange="[${framework_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="curios"
    mandatory=false
    versionRange="[${curios_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="controllable"
    mandatory=false
    versionRange="[0.18.0,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties."${mod_id}"]
    catalogueImageIcon="${mod_id}_icon.png"
    catalogueBackground="${mod_id}_background.png"
    configuredBackground="minecraft:textures/block/stone.png"
